version: '3.8'

services:
  backend:
    build:
      context: ./AsistenciaIndustry-Back
      dockerfile: Dockerfile
    container_name: asistencia_backend
    ports:
      - "5001:5001"
    env_file:
      - ./AsistenciaIndustry-Back/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./AsistenaciaIndustry-Front
      dockerfile: Dockerfile
    container_name: asistencia_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
